/*

 SELECTFILE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 37

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Bank of tiles. */
#define selectFileTileBank 0

#define selectFile_TileLen 38;

/* Start of tile array. */
extern unsigned char selectFileTile[];

/* End of SELECTFILE.H */
